#!/usr/bin/env python3
#
#  Convert CSS colors to rgba.
#
#  For example:
#
#    In>  foo: #fa0; 
#    Out> foo: rgba(255, 170, 0, 0.3);
#    In>  bar: #ffcc00;
#    Out> bar: rgba(255, 204, 0, 0.3);
 
import textchomp
import sys

t = textchomp.TextChomp(sys.stdin)

@t.pattern(r'(.*)#([0-9a-f]{3,6});')
def six(context, line):
    c = context.regex.group(2)
    if len(c) == 3:
        c1, c2, c3 = map(lambda x: int(int(x, 16)/15.0*255), c)
    else:
        c1, c2, c3 = map(lambda x: int(x, 16), (c[:2], c[2:4], c[4:]))
    print('{}rgba({}, {}, {}, 0.3);'.format(
        context.regex.group(1), c1, c2, c3))
t.run()
