#!/usr/bin/env python3
#
#  Remove duplicate lines.
#
#  Similar to the Unix "uniq" command, read lines from stdin and
#  output if it is not the same as the previous line.

import textchomp
import sys

t = textchomp.TextChomp(sys.stdin)

t.context.lastline = None

@t.eval('lastline != line')
def unique(ctx, line):
    sys.stdout.write(line)
    ctx.lastline = line

t.run()
